apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-invaders2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space-invaders
      env: staging
  template:
    metadata:
      labels:
        app: space-invaders
        env: staging
    spec:
      containers:
      - image: coursedemos/spaceinvaders:v2
        name: space-invaders2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
