apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-invaders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: space-invaders
      env: prod
  template:
    metadata:
      labels:
        app: space-invaders
        env: prod
    spec:
      containers:
      - image: us-docker.pkg.dev/stevedemo-july31/aug19/space-inv:v1.0
        name: space-invaders
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"


