apiVersion: v1
kind: Service
metadata:
  name: space-invader-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
      app: space-invaders
      env: prod
  type: LoadBalancer
